In [23]:
import torch
from torch import nn
nn.Linear(5,6)

Linear(in_features=5, out_features=6, bias=True)


In [28]:
import torch
from torch import nn

# Create a linear layer that takes 5 input features and outputs 6 features
linear_layer = nn.Linear(5, 10)

# Sample input
input_tensor = torch.randn(1, 5)  # Batch size of 1, 5 input features
output_tensor = linear_layer(input_tensor)
print(input_tensor)
output_tensor

tensor([[-0.4124,  1.1305, -1.2946,  0.4173, -0.8668]])


tensor([[ 0.4871, -0.4604, -0.0471,  0.4587,  0.1042, -0.0338, -0.7203, -0.4314,
         -0.6358, -1.1337]], grad_fn=<AddmmBackward0>)

In [34]:
input = torch.empty(2, 3)
print(input)
torch.ones_like(input,dtype=torch.bool).triu(1)


tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.0286e-38]])


tensor([[False,  True,  True],
        [False, False,  True]])

In [31]:
import tensorflow as tf

# Create a dense layer with 6 output units
dense_layer = tf.keras.layers.Dense(10)

# Sample input
input_tensor = tf.random.normal((1, 5))  # Batch size of 1, 5 input features
output_tensor = dense_layer(input_tensor)
print(input_tensor)
print(output_tensor)

tf.Tensor([[-0.14369045  0.9591966  -0.2701075  -1.1230993  -0.3981025 ]], shape=(1, 5), dtype=float32)
tf.Tensor(
[[ 0.36600307 -0.27534544 -0.49854833  0.52141446 -0.31856024  0.6927415
  -0.07178019  0.3842702  -0.0477876  -0.03145728]], shape=(1, 10), dtype=float32)


In [9]:
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc = nn.Linear(10, 5)
    
    def forward(self, x):
        return self.fc(x)

model = MyModel()
input_tensor = torch.randn(1, 10)
output = model(input_tensor)  # Calls forward internally


In [10]:
output

tensor([[-0.9293, -1.2216,  0.5267,  0.4138, -0.4850]],
       grad_fn=<AddmmBackward0>)

In [11]:
import tensorflow as tf

class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc = tf.keras.layers.Dense(5)
    
    def call(self, x):
        return self.fc(x)

model = MyModel()
input_tensor = tf.random.normal([1, 10])
output = model(input_tensor)  # Calls call internally
output

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[0.9049709 , 1.2881733 , 0.59506154, 2.1687467 , 0.7042613 ]],
      dtype=float32)>

In [14]:
import torch
import torch.nn as nn

class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(50, 1)
    
    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = SimpleModel()


In [15]:
import torch.optim as optim

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Dummy data
inputs = torch.randn(32, 10)
labels = torch.randn(32, 1)

# Training loop
for epoch in range(100):
    optimizer.zero_grad()  # Clear gradients
    outputs = model(inputs)  # Forward pass
    loss = criterion(outputs, labels)  # Compute loss
    loss.backward()  # Backward pass
    optimizer.step()  # Update weights


In [16]:
import tensorflow as tf

class SimpleModel(tf.keras.Model):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc1 = tf.keras.layers.Dense(50)
        self.relu = tf.keras.layers.ReLU()
        self.fc2 = tf.keras.layers.Dense(1)
    
    def call(self, x):
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = SimpleModel()


In [17]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
loss_fn = tf.keras.losses.MeanSquaredError()

# Dummy data
inputs = tf.random.normal([32, 10])
labels = tf.random.normal([32, 1])

# Training loop
for epoch in range(100):
    with tf.GradientTape() as tape:  # Start tracking gradients
        outputs = model(inputs)  # Forward pass
        loss = loss_fn(labels, outputs)  # Compute loss
    grads = tape.gradient(loss, model.trainable_variables)  # Backward pass
    optimizer.apply_gradients(zip(grads, model.trainable_variables))  # Update weights


In [18]:
import tensorflow as tf

# Define a simple model
class SimpleModel(tf.keras.Model):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc = tf.keras.layers.Dense(1)
    
    def call(self, x):
        return self.fc(x)

model = SimpleModel()

# Compile the model (specify loss function, optimizer, and metrics)
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),
              loss='mse',  # Mean Squared Error
              metrics=['mse'])

# Dummy data
inputs = tf.random.normal([32, 10])
labels = tf.random.normal([32, 1])

# Training using fit
history = model.fit(inputs, labels, epochs=100)


Epoch 1/100
1/1 [==============================] - 0s 418ms/step - loss: 2.4321 - mse: 2.4321
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 2.3538 - mse: 2.3538
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 2.2805 - mse: 2.2805
Epoch 4/100
1/1 [==============================] - 0s 10ms/step - loss: 2.2116 - mse: 2.2116
Epoch 5/100
1/1 [==============================] - 0s 11ms/step - loss: 2.1469 - mse: 2.1469
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 2.0861 - mse: 2.0861
Epoch 7/100
1/1 [==============================] - 0s 9ms/step - loss: 2.0289 - mse: 2.0289
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 1.9751 - mse: 1.9751
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 1.9245 - mse: 1.9245
Epoch 10/100
1/1 [==============================] - 0s 12ms/step - loss: 1.8769 - mse: 1.8769
Epoch 11/100
1/1 [==============================] - 0s 6ms/step - loss: 1

In [19]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a Sequential model
model = nn.Sequential(
    nn.Linear(10, 64),
    nn.ReLU(),
    nn.Linear(64, 1)
)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Dummy data
inputs = torch.randn(32, 10)
labels = torch.randn(32, 1)

# Training loop
for epoch in range(100):
    optimizer.zero_grad()  # Clear gradients
    outputs = model(inputs)  # Forward pass
    loss = criterion(outputs, labels)  # Compute loss
    loss.backward()  # Backward pass
    optimizer.step()  # Update weights
    print(f'Epoch [{epoch+1}/100], Loss: {loss.item():.4f}')


Epoch [1/100], Loss: 0.9704
Epoch [2/100], Loss: 0.9611
Epoch [3/100], Loss: 0.9522
Epoch [4/100], Loss: 0.9436
Epoch [5/100], Loss: 0.9354
Epoch [6/100], Loss: 0.9274
Epoch [7/100], Loss: 0.9197
Epoch [8/100], Loss: 0.9122
Epoch [9/100], Loss: 0.9049
Epoch [10/100], Loss: 0.8978
Epoch [11/100], Loss: 0.8909
Epoch [12/100], Loss: 0.8842
Epoch [13/100], Loss: 0.8777
Epoch [14/100], Loss: 0.8712
Epoch [15/100], Loss: 0.8649
Epoch [16/100], Loss: 0.8588
Epoch [17/100], Loss: 0.8527
Epoch [18/100], Loss: 0.8468
Epoch [19/100], Loss: 0.8410
Epoch [20/100], Loss: 0.8353
Epoch [21/100], Loss: 0.8297
Epoch [22/100], Loss: 0.8242
Epoch [23/100], Loss: 0.8188
Epoch [24/100], Loss: 0.8135
Epoch [25/100], Loss: 0.8082
Epoch [26/100], Loss: 0.8031
Epoch [27/100], Loss: 0.7980
Epoch [28/100], Loss: 0.7930
Epoch [29/100], Loss: 0.7880
Epoch [30/100], Loss: 0.7831
Epoch [31/100], Loss: 0.7782
Epoch [32/100], Loss: 0.7734
Epoch [33/100], Loss: 0.7688
Epoch [34/100], Loss: 0.7641
Epoch [35/100], Loss: 0

In [20]:
import tensorflow as tf

# Define a Sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(10,)),
    tf.keras.layers.Dense(1)
])

# Compile the model (specify loss, optimizer, and metrics)
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),
              loss='mean_squared_error',  # Loss function
              metrics=['mse'])  # Metrics

# Dummy data
inputs = tf.random.normal([32, 10])
labels = tf.random.normal([32, 1])

# Train the model using fit
history = model.fit(inputs, labels, epochs=100, batch_size=32)


Epoch 1/100
1/1 [==============================] - 0s 260ms/step - loss: 1.6324 - mse: 1.6324
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 1.4857 - mse: 1.4857
Epoch 3/100
1/1 [==============================] - 0s 11ms/step - loss: 1.3724 - mse: 1.3724
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 1.2829 - mse: 1.2829
Epoch 5/100
1/1 [==============================] - 0s 16ms/step - loss: 1.2106 - mse: 1.2106
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 1.1514 - mse: 1.1514
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 1.1022 - mse: 1.1022
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 1.0608 - mse: 1.0608
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 1.0248 - mse: 1.0248
Epoch 10/100
1/1 [==============================] - 0s 10ms/step - loss: 0.9931 - mse: 0.9931
Epoch 11/100
1/1 [==============================] - 0s 14ms/step - loss: 

In [21]:
# encoder in tensorflow
import tensorflow as tf

class ResidualBlock(tf.keras.layers.Layer):
    def __init__(self, input_channels, output_channels):
        super(ResidualBlock, self).__init__()
        self.conv1 = tf.keras.layers.Conv2D(output_channels, kernel_size=3, padding='same')
        self.conv2 = tf.keras.layers.Conv2D(output_channels, kernel_size=3, padding='same')
        self.activation = tf.keras.layers.ReLU()
        
        # Skip connection
        if input_channels != output_channels:
            self.skip = tf.keras.layers.Conv2D(output_channels, kernel_size=1, padding='same')
        else:
            self.skip = None

    def call(self, x):
        residual = x
        x = self.conv1(x)
        x = self.activation(x)
        x = self.conv2(x)

        # If skip connection, align dimensions
        if self.skip is not None:
            residual = self.skip(residual)

        return self.activation(x + residual)

class VAE_Encoder(tf.keras.Model):
    def __init__(self):
        super(VAE_Encoder, self).__init__()
        # Layers are defined in the constructor
        self.conv1 = tf.keras.layers.Conv2D(128, kernel_size=3, padding='same')
        
        # Define residual blocks and convolution layers
        self.residual1 = ResidualBlock(128, 128)
        self.residual2 = ResidualBlock(128, 128)
        self.downsample1 = tf.keras.layers.Conv2D(128, kernel_size=3, strides=2, padding='valid')  # Downsampling
        self.residual3 = ResidualBlock(128, 256)
        self.residual4 = ResidualBlock(256, 256)
        self.downsample2 = tf.keras.layers.Conv2D(256, kernel_size=3, padding='valid')
        self.residual5 = ResidualBlock(256, 512)
        self.residual6 = ResidualBlock(512, 512)
        self.downsample3 = tf.keras.layers.Conv2D(512, kernel_size=3, strides=2, padding='valid')  # Downsampling
        
        self.residual7 = ResidualBlock(512, 512)
        self.attention = tf.keras.layers.Attention()
        self.group_norm = tf.keras.layers.LayerNormalization()
        self.silu = tf.keras.layers.Activation('swish')
        self.conv2 = tf.keras.layers.Conv2D(8, kernel_size=3, padding='same')
        self.conv3 = tf.keras.layers.Conv2D(8, kernel_size=1)

    def call(self, x, noise):
        # Input image x (batch_size, height, width, channels)
        # noise: (batch_size, height/8, width/8, out_channels)
        
        # Apply each layer sequentially
        x = self.conv1(x)  # First convolution, change channels from 3 to 128
        x = self.residual1(x)
        x = self.residual2(x)
        x = self.downsample1(x)  # Downsampling by stride 2
        
        x = self.residual3(x)
        x = self.residual4(x)
        x = self.downsample2(x)  # Downsampling again
        
        x = self.residual5(x)
        x = self.residual6(x)
        x = self.downsample3(x)  # Final downsampling
        
        x = self.residual7(x)
        
        # Attention block (not fully implemented here, but placeholder)
        # x = self.attention([x, x])  # Use self-attention
        
        x = self.group_norm(x)  # Normalization
        x = self.silu(x)  # SiLU activation
        x = self.conv2(x)  # Reduce channels to 8
        x = self.conv3(x)  # Another convolution to refine
        
        # Split into two tensors: mean and log_variance
        mean, log_variance = tf.split(x, num_or_size_splits=2, axis=-1)
        log_variance = tf.clip_by_value(log_variance, -30, 28)  # Clamping log_variance
        
        # Calculate variance and standard deviation
        variance = tf.exp(log_variance)
        stdev = tf.sqrt(variance)
        
        # Add noise to the mean and standard deviation
        x = mean + stdev * noise
        
        # Scale the result
        x *= 0.18215
        
        return x
